Impact and deliverable improvement
FundImpact/fundimpact-frontend pull request #128
Opened 2020-09-08 10:35 UTC by realgcoding

fix #114 
added no context available if no option available for select 
defined types for deliverable and impact responses

2020-09-09 02:11 UTC, ShadabFaiz requested changes

2020-09-09 02:11 UTC, ShadabFaiz commented on debug.log
> +[0904/013449.845:ERROR:exception_snapshot_win.cc(98)] thread ID 26900 not found in process
What is this file for?

2020-09-09 02:11 UTC, ShadabFaiz commented on src/components/Deliverable/DeliverableTrackline.tsx
> +				} catch (err) {}
log w/e error we are getting here or mention why we are not logging it For error logging dont use console.log, instead use console.error

2020-09-09 07:54 UTC, realgcoding commented on src/components/Table/Deliverable/Deliverable.tsx
> +							{page * 10 + i + 1}
will change it

2020-09-14 06:19 UTC, ShadabFaiz approved these changes

2020-09-14 06:19 UTC, merged