Refinements/remove warning errors
FundImpact/fundimpact-frontend pull request #67
Opened 2020-08-24 12:36 UTC by realgcoding

2020-08-25 03:42 UTC, ShadabFaiz requested changes
2 things to note here.
1.  The PR is outdated. Update it from `development` branch.
2. Even though the test cases are being passed. There are some errors during running test case related to event being fire.

2020-08-25 14:03 UTC, anirudh411 approved these changes

2020-08-27 06:59 UTC, anirudh411 requested changes

2020-08-27 06:59 UTC, anirudh411 commented on src/components/Deliverable/DeliverableTarget.tsx
> +			if (data.deliverableCategoryUnitList && data.deliverableCategoryUnitList.length) {
can be simplified with `?`

2020-08-27 06:59 UTC, anirudh411 commented on src/components/Deliverable/DeliverableTarget.tsx
> +		console.log("hey", currentCategory);
remove console logs

2020-08-27 08:57 UTC, anirudh411 approved these changes

2020-08-30 16:16 UTC, ShadabFaiz commented on src/components/Deliverable/DeliverableTarget.tsx
> +			if (data.deliverableCategoryUnitList && data.deliverableCategoryUnitList.length) {
done

2020-08-30 16:16 UTC, ShadabFaiz commented on src/components/Deliverable/DeliverableTarget.tsx
> +		console.log("hey", currentCategory);
done

2020-08-30 16:17 UTC, anirudh411 approved these changes

2020-08-30 16:21 UTC, ShadabFaiz approved these changes
Needs alot of fixes...but accepting it now..

2020-08-30 16:22 UTC, merged