budget table fixed
FundImpact/fundimpact-frontend pull request #68
Opened 2020-08-24 14:31 UTC by shubhamsingh3211

2020-08-25 02:56 UTC, ShadabFaiz requested changes
There are some issues in the test cases of some of the budget related files such as `BudgetLineItemDialog.test.tsx`.

2020-08-25 14:01 UTC, anirudh411 requested changes

2020-08-26 07:02 UTC, ShadabFaiz approved these changes

2020-08-26 07:21 UTC, anirudh411 approved these changes

2020-08-26 07:25 UTC, anirudh411 commented
Hi @shubhamsingh3211  PR looks good. Just remove the code smells

2020-08-26 09:28 UTC, merged