fixed data-refersh on adding a project ,for after creating a delivera…
FundImpact/fundimpact-frontend pull request #99
Opened 2020-08-31 11:01 UTC by realgcoding

Implemented impact category mapping with on unit for impact unit form | bug fixes data refresh on project creation | data refresh for deliverable category and impact category | data refresh on deliverable target creation

2020-08-31 12:11 UTC, anirudh411 requested changes

2020-08-31 12:11 UTC, anirudh411 commented on src/components/Deliverable/DeliverableTarget.tsx
> +						let deliverableTargets: any[] = dataRead?.deliverableTargetList
can `deliverableTargets` have type other than `any`?

2020-09-01 05:34 UTC, anirudh411 approved these changes

2020-09-01 06:37 UTC, ShadabFaiz approved these changes

2020-09-01 06:37 UTC, merged